### ISSUE TITLE
Tool create global group for delegation

### ISSUE THREAD

**Issue by PatrickOnGit** [merddyin/ADDeploy#5]
The tool is creating global groups to delegate access to AD.
Best practice is to use either domain local security groups to delegate rights within a domain or universal security groups to delegate rights within a domain or within AD configuration naming context.
Taking into account that cloud managed processes use universal groups, all groups created using ADDeploy should be universal security groups.
https://learn.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-group-writeback-v2
https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2003/cc755692(v=ws.10)
https://learn.microsoft.com/en-us/security/privileged-access-workstations/privileged-access-deployment

**Comment by merddyin** [comment]
An argument could be made for using Domain Local groups, but not Universal Groups.

**Comment by PatrickOnGit** [comment]
The argument can be for both. When delegating access to configuration naming context, that includes access to PKI, DNS-N, DFS-R and many more, one must use universal groups. This is because they exist as part of the global catalog and are not bound to a domain. Domain Local as well as global group are replicated as part of the partial replica set in the global catalog, but actually only exist in the domain in which they were created. If you use a root DC creating a domain local group (or global group) and grant access to configuration naming context, for instance the Public Key container, users can access the public key container as long as the connect to a root DC. But if they connect to a child DC, which also contains a writable copy of the configuration naming context, they have no access. Therefore, using Universal Groups to grant access to Active Directory is a very valid option.
Now, the tool in its current published version, only delegates access within the Tier-0 to Tier-2 OU structure within the domain it was deployed. Delegation using universal groups is therefore not a necessity. But, to be consistent, if delegation is expanded to the configuration naming context, as it should, then creating universal groups for all delegations would be the right choice.

**Comment by merddyin** [comment]
So, I see your perspective on this one, and you are correct in terms of your premise, however there are other factors to consider. The key factor that requires consideration is that of max token size. While the current max should be more than sufficient for most cases, the majority of the AD environments I have encountered have been around since 2000, and if only in-place upgrades were used, then the max token size is not increased. I can't find the specific reference off hand at the moment, but the different group types have different bit size values when it comes to calculating token size, which was one of the considerations. As you mention, the tool does not currently delegate forest level permissions of any type, which is presently by design. This framework is based on Microsoft's ESAE framework, and leverages the concept of the 'Gold Card Administrator' which should typically consist of 2-4 (max) individuals with admin accounts that are embedded in the Administrators group for the domain. These users can perform most actions related to GPO's and the OU structure, to include management of ACLs, and they can even log into DCs, but they cannot perform forest level tasks either. To perform forest level actions, a GCA would promote another account temporarily into DA/EA/SA as needed for the duration of the task, and then remove them again. Part of the point of the framework is to protect environments from themselves...I cannot tell you how many times I have been in breached environments where the admins just did whatever was most convenient (e.g. add user to DA rather than properly delegate server access, or give DA because some product vendor couldn't be bothered to figure out what access they really needed). I can tell you that in 70% or more of environments that I have been in, access is severely over-provisioned. The simple fact is that you shouldn't need the ability to modify things like GPO links and DFS every day at all times on your admin...you typically need the access for a short time to perform a specific task. If you don't have the access, then accidental exposure of the account is less of an impact than it might otherwise be...no matter how smart and determined of an admin you are, at some point you _will_ make a mistake, and it only takes one such mistake to result in a major breach. Look at the LastPass breach...one guy used his account in the wrong place one time (supposedly), and now millions of users passwords are likely exposed. The fact is, most don't _need_ the access all the time, the right people just need to be able to _obtain_ the access when it is actually necessary. That's what this framework is intended to accomplish.

**Comment by merddyin** [comment]
So, for now, I'm not going to make this change, for all of the various reasons I've outlined above. That said, if you feel really strongly about it, I believe you can simply comment out the line where the groupType is being set, and it should create as a Domain Local security group by default.
